[package]
name = "calc"
version = "0.1.3"
edition = "2021"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
lalrpop-util = { version = "^0.19", features = ["lexer"] }
regex = "1"
colored = "2.0.0"
exitcode = "1.1.2"
rustyline = "9.1.0"